src/Entity/Employes.php
<?php

namespace App\Entity;

use App\Repository\EmployesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployesRepository::class)
 */
class Employes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $ModifiedAt;

    /**
     * @ORM\OneToMany(targetEntity=HeureProjet::class, mappedBy="Employe")
     */
    private $heureProjets;

    public function __construct()
    {
        $this->heureProjets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->ModifiedAt;
    }

    public function setModifiedAt(?\DateTimeImmutable $ModifiedAt): self
    {
        $this->ModifiedAt = $ModifiedAt;

        return $this;
    }

    /**
     * @return Collection|HeureProjet[]
     */
    public function getHeureProjets(): Collection
    {
        return $this->heureProjets;
    }

    public function addHeureProjet(HeureProjet $heureProjet): self
    {
        if (!$this->heureProjets->contains($heureProjet)) {
            $this->heureProjets[] = $heureProjet;
            $heureProjet->setEmploye($this);
        }

        return $this;
    }

    public function removeHeureProjet(HeureProjet $heureProjet): self
    {
        if ($this->heureProjets->removeElement($heureProjet)) {
            // set the owning side to null (unless already changed)
            if ($heureProjet->getEmploye() === $this) {
                $heureProjet->setEmploye(null);
            }
        }

        return $this;
    }
}

src/Entity/Projects.php
<?php

namespace App\Entity;

use App\Repository\ProjectsRepository;
use Cocur\Slugify\Slugify;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ProjectsRepository::class)
 * @UniqueEntity("code")
 */
class Projects
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateEntree;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DateDelai;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="projects")
     */
    private $options;

    /**
     * @ORM\ManyToOne(targetEntity=TypeProjet::class, inversedBy="Projects")
     *
     */
    private $TypeProjet;

    /**
     *
     * @ORM\ManyToOne  (targetEntity=Clients::class, inversedBy="projects")
     *
     */
    private $clients;

    /**
     * @ORM\OneToMany(targetEntity=HeureProjet::class, mappedBy="project")
     */
    private $heureProjets;






    public function __construct()
    {
        $this->options = new ArrayCollection();
        $this->heureProjets = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }
    public function getSlug(): string
    {
        return  (new Slugify())->slugify($this->code);

    }

    public function getDateEntree(): ?DateTimeInterface
    {
        return $this->DateEntree;
    }

    public function setDateEntree(DateTimeInterface $DateEntree): self
    {
        $this->DateEntree = $DateEntree;

        return $this;
    }

    public function getDateDelai(): ?DateTimeInterface
    {
        return $this->DateDelai;
    }

    public function setDateDelai(?DateTimeInterface $DateDelai): self
    {
        $this->DateDelai = $DateDelai;

        return $this;
    }



    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProject($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProject($this);
        }

        return $this;
    }


    /**
     * @return DateTimeInterface|null
     */
    public function getStartDate(): ?DateTimeInterface {
        return $this->getDateEntree();
    }

    public function getTypeProjet(): ?TypeProjet
    {
        return $this->TypeProjet;
    }

    public function setTypeProjet(TypeProjet $TypeProjet): self
    {
        $this->TypeProjet = $TypeProjet;

        return $this;
    }



    public function getClients(): ?Clients
    {
        return $this->clients;
    }

    public function setClients(?Clients $clients): self
    {
        $this->clients = $clients;

        return $this;
    }

    /**
     * @return Collection|HeureProjet[]
     */
    public function getHeureProjets(): Collection
    {
        return $this->heureProjets;
    }

    public function addHeureProjet(HeureProjet $heureProjet): self
    {
        if (!$this->heureProjets->contains($heureProjet)) {
            $this->heureProjets[] = $heureProjet;
            $heureProjet->setProject($this);
        }

        return $this;
    }

    public function removeHeureProjet(HeureProjet $heureProjet): self
    {
        if ($this->heureProjets->removeElement($heureProjet)) {
            // set the owning side to null (unless already changed)
            if ($heureProjet->getProject() === $this) {
                $heureProjet->setProject(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->code;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Clients;
use App\Entity\Option;
use App\Entity\Projects;
use App\Entity\TypeProjet;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class ProjectType extends AbstractType
{

    public function __construct(private UrlGeneratorInterface $urlGenerator)
    {
        
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code')
            ->add('DateEntree',DateTimeType::class,[
                'date_widget' => 'single_text',
                'time_widget' => 'single_text',
                'days' => range(1,31),
                'years' => range(1970,2100),
            ])
            ->add('DateDelai',DateTimeType::class,[
                'years' => range(1970,2100),
            ])

            ->add('description')
//            ->add('options' , EntityType:: class, [
//                'class' => Option::class,
//                'choice_label' => 'name',
//                'multiple' => true,
//                'required' => false,
//
//            ])
            ->add('options' , SearchableEntityType::class, [
                'class'=> Option::class,
                'multiple' => true,
                'search' => $this->urlGenerator->generate("api_options"),
                'label_property' =>'name'
            ])
            ->add("TypeProjet", EntityType::class, [
                'choice_label' => 'name',
                'class' => TypeProjet::class,
                'required' => false
            ])
            ->add("Clients", EntityType::class, [
                'choice_label' => 'name',
                'class' => Clients::class,
                'multiple' => false,
                'required' => false,
                

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Projects::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;


use App\Entity\ProjectSearch;
use App\Form\ProjectSearchType;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ProjectsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;


class ProjectController  extends AbstractController
{

    private EntityManagerInterface $em;
    private ProjectsRepository $repository;

    public function __construct(ProjectsRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
         $this->em = $em;
    }

    /**
     * index
     * @Route("/Projects" , name="Projects.index" )
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request):Response
    {

        $search = new ProjectSearch();
        $form = $this->createForm(ProjectSearchType::class, $search);
        $form->handleRequest($request);
        dump($search);
        $query = $this->repository->findAllVisible($search);

        $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );
        dump($query->getArrayResult());
        return $this->render('projects/index.html.twig', [
            'current_menu' => 'projects',
            'projects' => $pagination,
            'form' => $form->createView()
        ]);
    }

    /**
     * show
     * @Route("/Projects/{slug}-{id}" , name="Projects.show", requirements={"slug": "[a-z0-9\-]*"} )
     * @param $slug
     * @param $id
     * @return Response
     */
    public function show($slug, $id): Response
    {


        $projet = $this->repository->find($id);
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        dump($serializer->serialize($projet,'json', [AbstractNormalizer::ATTRIBUTES => ['code', 'id']]));
    //dump($projet);

        if ($projet->getSlug() !== $slug) {
            
            return $this->redirectToRoute('Projects.show',[
                'id' => $projet->getId(),
                'slug' => $projet->getSlug()
            ],301);
        }
        $heureprojects = $projet->getHeureProjets()->getValues();
        return $this->render('projects/show.html.twig', [
            'projet' => $projet,
            'current_menu' => 'projects',
            'heureprojects' => $heureprojects
        ]);
    }

    /**
     * pdf
     * @Route("/Projects/{slug}-{id}/pdf" , name="Projects.pdf" , requirements={"slug": "[a-z0-9\-]*"})
     * @param $slug
     * @param $id
     * @return Response
     */
    public function pdf($slug, $id): Response
    {
        $projet = $this->repository->find($id);
        dump($this->repository->findOneByIdJoinedClient($id));
        if ($projet->getSlug() !== $slug) {

            return $this->redirectToRoute('Projects.show',[
                'id' => $projet->getId(),
                'slug' => $projet->getSlug()
            ],301);
        }
        $heureprojects = $projet->getHeureProjets()->getValues();

        $options = new Options();
        $options->set('defaultFont', 'Roboto');

        // instantiate and use the dompdf class
        $dompdf = new Dompdf($options);
        $html = $this->renderView('pdf/project.html.twig',[
            'title' => "titrepdf",
            'project' => $projet
        ]);
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('A4', 'landscape');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser
        $dompdf->stream("document.pdf", [
            "Attachment" => false
        ]);

        /*return new Response($dompdf->stream("doc"), [
            "Attachment" => false
        ]);*/
        return new Response('', 200, [
            'Content-Type' => 'application/pdf',
        ]);

    }

    /**
     * pdf
     * @Route("/Projects/{slug}-{id}/json" , name="Projects.json" , requirements={"slug": "[a-z0-9\-]*"})
     * @param $slug
     * @param $id
     * @return JsonResponse
     */
        public function jsonn($slug, $id): JsonResponse
    {
        $projet = $this->repository->find($id);
        dump($this->repository->findOneByIdJoinedClient($id));
        /*if ($projet->getSlug() !== $slug) {

            return $this->redirectToRoute('Projects.show',[
                'id' => $projet->getId(),
                'slug' => $projet->getSlug()
            ],301);
        }*/
        $heureprojects = $projet->getHeureProjets()->getValues();



        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $json = $serializer->serialize($projet, 'json',[
            AbstractNormalizer::ATTRIBUTES => ['code', 'id','DateEntree','DateDelai','TypeProjet','description'],
            /*AbstractObjectNormalizer::ENABLE_MAX_DEPTH => false*/
        ]);
        //return new JsonResponse($json);
        return new JsonResponse($json,200,[],true);

    }
}

src/Controller/api/ProjectsController.php
<?php


namespace App\Controller\api;



use App\Repository\ProjectsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProjectsController extends AbstractController
{
    #[Route('/api/projects', name: 'api_projects')]
    public function index(Request $request, ProjectsRepository $repository)
    {

        return $this->json($repository->search($request->get("q")));
    }
}

templates/projects/_projects.html.twig
<tr>
    <td><a href="{{ path('Projects.show',{id: project.id,slug: project.getslug}) }}" class="btn btn-primary btn-sm" >{{project.id}}</a></td>
    <td>{{project.code}}</td>
    <td>{{ project.getClients.name ?? "null" }}</td>
    <td>{{project.dateentree|date("m/d/Y")}}</td>
    <td>{{project.dateDelai|date("m/d/Y")}}</td>
    <td>{{project.getTypeprojet.name ?? "null"}}</td>
    <td>{{project.description | nl2br}}</td>

</tr>

templates/projects/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Projects
{% endblock %}

{% block body %}
    
    <div class="container border mb-2 p-2">
        <h1>Bienvenu sur la page Projects</h1>
    </div>

        <div class="row">
            <div class="col-3" >
                <div class="container border pt-3">
                    <h2>Recherche</h2>
                    {{form_start(form)}}
                    <div class="form-row row">

                        {{form_row(form.TypeProjet)}}
                        {{ form_rest(form) }}
                        {{form_end(form)}}
                        <button class="btn btn-primary" type="submit">Soumettre</button>
                        <a class="btn btn-info" href="{{ path('Projects.index') }}"> Reset</a>
                    </div>




                </div>
            </div>
            <div class="col" >
                <div class="container mt-2">


                    <table class="table table-hover table-striped">
                        <tr>
                            <th>Id</th>
                            <th>Code {{ knp_pagination_sortable(projects, '', 'p.code') }}</th>
                            <th>Client {{ knp_pagination_sortable(projects, '', 'c.name') }}</th>
                            <th>Date Entree</th>
                            <th>Delai</th>
                            <th>Type</th>
                            <th>Description</th>
                        </tr>


                        {% for project in projects %}
                            {% include "projects/_projects.html.twig" %}

                        {% else %}
                            <tr>
                                <td colspan="6">Aucun record</td>
                            </tr>

                        {% endfor %}




                    </table>

                    <div class="container">
                        <h4>Pagination <span class="count">{{ projects.getTotalItemCount }}</span></h4>
                        <div class="navigation">
                            {{ knp_pagination_render(projects) }}
                        </div>
                    </div>

                </div>

            </div>
        </div>




{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
        //$('select').select2();
    </script>
{% endblock %}

templates/projects/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    project
{% endblock %}
{% block body %}

    <div class="container border border-primary">
        
        <div class="row my-3">
            <div class="col">
                <a href="{{ path('admin.Projects.edit' , {'id':projet.id}) }}" class="btn btn-secondary">edit</a>

            </div>
            <div class="col">
                <a href="{{ path('admin.Projects.delete', {'id':projet.id}) }}" class="btn btn-danger">Delete</a>

            </div>
                                </div>
        <div class="row py-2">
            <div class="col-md-8 border">
                <h1>Page Projet</h1>
                <h3>Description</h3>
                <p>
                {{ projet.description }}
                </p>
                <p>
                {{ projet.description | nl2br }}
                </p>
                <h3>Client</h3>
                <p>{{ projet.clients.name ?? "Nom Client inconnu :(" }}</p>
                {% if projet.clients %}
                <a href="{{ path('clients_show',{'id': projet.clients.id}) }}">{{ projet.clients.name }}</a>
                {% else %}
                <p>Client non renseigné</p>
                {% endif %}
                <h3>
                    Type Project
                </h3>
                {% if projet.typeProjet %}
                <a href="{{ path('type_projet_show',{'id': projet.typeProjet.id}) }}" class="btn btn-secondary">{{ projet.typeProjet.name }}</a>
                {% else %}
                    <p>Type projet non renseigné</p>
                {% endif %}
                <h3>Actions:</h3>
                <ul>
                    <li><a href="{{ path('Projects.pdf', {'id': projet.id,'slug': projet.slug}) }}" class="btn btn-primary">pdf</a>
                    </li>
                    <li><a href="{{ path('Projects.json', {'id': projet.id,'slug': projet.slug}) }}" class="btn btn-primary">json</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 border">
                <h2>
                    <span id="projet_id">{{projet.code}}</span>
                    {{ dump(projet.clients) }}
                    {{ dump(projet.clients.name ?? "null") }}

                </h2>
            </div>
        </div>
    </div>
    <div class="container">
        <h3>Heure Project</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>id</td>
                    <td>temps</td>
                    <td>Actions</td>
                </tr>

            </thead>
            {% for heure_projet in heureprojects %}
                <tr>
                    <td>{{ heure_projet.id }}</td>
                    <td>{{ heure_projet.duree }}</td>
                    <td>

                            <a href="{{ path('heure_projet_show',{'id': heure_projet.id}) }}" class="btn btn-sm btn-dark" style="display: inline-block">{{ heure_projet.id }} </a>

                            <div style="display: inline-block">
                                {{ include('heure_projet/_delete_form.html.twig') }}
                            </div>



                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="2">No Records</td>
                </tr>
            {% endfor %}
            <tfooter>
                <tr>
                    <td colspan="2"></td>
                    <td>
                        <a href="{{ path('heure_projet_new') }}" class="btn btn-outline-secondary">new</a>

                    </td>
                </tr>
            </tfooter>
        </table>

    </div>
{% endblock %}
{% block javascripts %}
   {{ encore_entry_script_tags('Project') }}
{% endblock %}