src/Entity/HeureProjet.php
<?php

namespace App\Entity;

use App\Repository\HeureProjetRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HeureProjetRepository::class)
 */
class HeureProjet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;



    /**
     * @ORM\Column(type="float")
     */
    private $duree;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isHidden;

    /**
     * @ORM\ManyToOne(targetEntity=Projects::class, inversedBy="heureProjets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $project;

    /**
     * @ORM\ManyToOne(targetEntity=Employes::class, inversedBy="heureProjets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Employe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getEmploye(): ?Employes
    {
        return $this->Employe;
    }

    public function setEmploye(?Employes $Employe): self
    {
        $this->Employe = $Employe;

        return $this;
    }

    public function getDuree(): ?float
    {
        return $this->duree;
    }

    public function setDuree(float $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getIsHidden(): ?bool
    {
        return $this->isHidden;
    }

    public function setIsHidden(bool $isHidden): self
    {
        $this->isHidden = $isHidden;

        return $this;
    }

    public function getProject(): ?Projects
    {
        return $this->project;
    }

    public function setProject(?Projects $project): self
    {
        $this->project = $project;

        return $this;
    }
}

src/Form/HeureProjetType.php
<?php

namespace App\Form;

use App\Entity\Employes;
use App\Entity\HeureProjet;
use App\Entity\Projects;
use App\Entity\Users;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HeureProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Date')
            ->add('duree')
            ->add('isHidden')
            ->add('Employe',EntityType::class ,[
                "class" => Employes::class,
                "choice_label" => 'name'
            ])
            ->add('project', EntityType::class ,[
                "class" => Projects::class,
                "choice_label" => 'code'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => HeureProjet::class,
        ]);
    }
}

src/Controller/HeureProjetController.php
<?php

namespace App\Controller;

use App\Classes\Month;
use App\Entity\HeureProjet;
use App\Form\HeureProjetType;
use App\Repository\EmployesRepository;
use App\Repository\HeureProjetRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/heureprojet")
 */
class HeureProjetController extends AbstractController
{
    /**
     * @Route("/", name="heure_projet_index", methods={"GET"})
     * @param HeureProjetRepository $heureProjetRepository
     * @return Response
     */
    public function index(HeureProjetRepository $heureProjetRepository): Response
    {
        $month = new Month(4,2021);
        //dump($heureProjetRepository->findbymonth($month));
        return $this->render('heure_projet/index.html.twig', [
            'heure_projets' => $heureProjetRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="heure_projet_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request, EmployesRepository $repository): Response
    {
        $heureProjet = new HeureProjet();
        if ($request->get("d") &&  $request->get("m") && $request->get("y"))
        {
            $heureProjet->setDate(new \DateTime($request->get("y")."-".$request->get("m")."-".$request->get("d")));
        }
        if ($request->get("e")){
            dump($repository->find($request->get("e")));
            $heureProjet->setEmploye($repository->find($request->get("e")));
        }
        $form = $this->createForm(HeureProjetType::class, $heureProjet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($heureProjet);
            $entityManager->flush();

            return $this->redirectToRoute('heure_projet_index');
        }

        return $this->render('heure_projet/new.html.twig', [
            'heure_projet' => $heureProjet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="heure_projet_show", methods={"GET"})
     */
    public function show(HeureProjet $heureProjet): Response
    {
        return $this->render('heure_projet/show.html.twig', [
            'heure_projet' => $heureProjet,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="heure_projet_edit", methods={"GET","POST"})
     * @param Request $request
     * @param HeureProjet $heureProjet
     * @return Response
     */
    public function edit(Request $request, HeureProjet $heureProjet): Response
    {
        $form = $this->createForm(HeureProjetType::class, $heureProjet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('heure_projet_index');
        }

        return $this->render('heure_projet/edit.html.twig', [
            'heure_projet' => $heureProjet,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="heure_projet_delete", methods={"DELETE"})
     * @param Request $request
     * @param HeureProjet $heureProjet
     * @return Response
     */
    public function delete(Request $request, HeureProjet $heureProjet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$heureProjet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($heureProjet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('heure_projet_index');
    }
}

templates/heure_projet/_delete_form.html.twig
<form method="post" action="{{ path('heure_projet_delete', {'id': heure_projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ heure_projet.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/heure_projet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit HeureProjet{% endblock %}

{% block body %}
    <h1>Edit HeureProjet</h1>

    {{ include('heure_projet/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('heure_projet_index') }}">back to list</a>

    {{ include('heure_projet/_delete_form.html.twig') }}
{% endblock %}

templates/heure_projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HeureProjet index{% endblock %}

{% block body %}
    <h1>HeureProjet index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Projects</th>
                <th>Date</th>
                <th>Duree</th>
                <th>IsHidden</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for heure_projet in heure_projets %}
            <tr>
                <td>{{ heure_projet.id }}</td>
                <td>{{ heure_projet.project.code }}</td>
                <td>{{ heure_projet.Date ? heure_projet.Date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ heure_projet.duree }}</td>
                <td>{{ heure_projet.isHidden ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('heure_projet_show', {'id': heure_projet.id}) }}">show</a>
                    <a href="{{ path('heure_projet_edit', {'id': heure_projet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('heure_projet_new') }}">Create new</a>
{% endblock %}

templates/heure_projet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New HeureProjet{% endblock %}

{% block body %}
    <div class="container">
        <h1>Create new HeureProjet</h1>

        {{ include('heure_projet/_form.html.twig') }}

        <a href="{{ path('heure_projet_index') }}">back to list</a>

    </div>
{% endblock %}

templates/heure_projet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HeureProjet{% endblock %}

{% block body %}
    <h1>HeureProjet</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ heure_projet.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ heure_projet.Date ? heure_projet.Date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ heure_projet.duree }}</td>
            </tr>
            <tr>
                <th>Employe</th>
                <td>{{ heure_projet.employe.email }}</td>
            </tr>
            <tr>
                <th>IsHidden</th>
                <td>{{ heure_projet.isHidden ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('heure_projet_index') }}">back to list</a>

    <a href="{{ path('heure_projet_edit', {'id': heure_projet.id}) }}">edit</a>

    {{ include('heure_projet/_delete_form.html.twig') }}
{% endblock %}